name: Publish Package

description: Manual workflow to publish both Elixir (mix) and npm packages, and tag the release in git.

on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version (e.g. 0.1.0)
        required: true
        type: string

env:
  MIX_ENV: prod

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.16'
          otp-version: '26.2'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Set version in mix.exs
        run: |
          sed -i "s/@version \".*\"/@version \"${{ github.event.inputs.version }}\"/" mix.exs

      - name: Set version in npm_package/package.json
        run: |
          jq ".version = \"${{ github.event.inputs.version }}\"" npm_package/package.json > tmp.json && mv tmp.json npm_package/package.json

      - name: Set version in README.md
        run: |
          sed -i "s/{:ckeditor5_phoenix, \"~> [0-9]\+\.[0-9]\+\.[0-9]\+\"}/{:ckeditor5_phoenix, \"~> ${{ github.event.inputs.version }}\"}/" README.md

      - name: Install Elixir dependencies
        run: mix deps.get

      - name: Install npm dependencies
        run: npm ci
        working-directory: ./npm_package

      - name: Publish npm package
        run: npm publish --access public
        working-directory: ./npm_package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish Hex package
        run: |
          mix prepare.publish
          mix hex.publish --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}

      - name: Configure Git
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      - name: Commit and push version bump
        run: |
          git add mix.exs npm_package/package.json README.md
          git commit -m "build: bump versions to v${{ github.event.inputs.version }}"
          git push

      - name: Create git tag
        run: |
          git tag v${{ github.event.inputs.version }}
          git push origin v${{ github.event.inputs.version }}
